[project]
authors = ["josh <joshuaholman5@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ml-project"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.14"
numpy = ">=2.2.5,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.1,<4"
seaborn = ">=0.13.2,<0.14"
urllib3 = ">=2.4.0,<3"
jupyter = ">=1.1.1,<2"
wordcloud = ">=1.9.4,<2"
streamlit = ">=1.44.1,<2"
nltk = ">=3.9.1,<4"
nbconvert = ">=7.16.6,<8"
nbdime = ">=4.0.2,<5"
marimo = ">=0.13.2,<0.14"
kagglehub = ">=0.3.8,<0.4"
anthropic = ">=0.50.0,<0.51"
cartopy = ">=0.24.0,<0.25"
plotly = ">=6.0.1,<7"
scikit-learn = ">=1.6.1,<2"
pygeohash = ">=1.2.0,<2"
sentence-transformers = ">=4.1.0,<5"
pytorch = ">=2.6.0,<3"
ruff = ">=0.11.7,<0.12"

[pypi-dependencies]
lets-plot = ">=4.6.2, <5"

[target.linux-64.dependencies]
tf-keras = ">=2.18.0,<3"
tensorflow = ">=2.18.0,<3"
